name: Sync-Gitee
on:
  push:
    branches: [main]

jobs:
  push-to-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: |
          git config --global init.defaultBranch main
          git init
          git remote add origin https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git fetch --all
          for branch in `git branch -a | grep remotes | grep -v HEAD`; do
            git branch --track ${branch##*/} $branch
          done
        env:
          GITHUB_REPOSITORY: qiect/pcnav
          #GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          #GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
          
      - name: Push to Gitee
        run: |
          echo "stop!"
          #remote_repo="https://${GITEE_USERNAME}:${GITEE_PASSWORD}@gitee.com/${GITEE_REPOSITORY}.git"
          #git remote add gitee "${remote_repo}"
          #git show-ref # useful for debugging
          #git branch --verbose
          # publish all
          #git push --all --force gitee
          #git push --tags --force gitee
        env:
          GITEE_REPOSITORY: qiect/pcnav
          #GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          #GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
